### PR TITLE
Renew Rspec syntax to use `expect`

### PR DESCRIPTION
**Pull request by styd**
Try to use the latest Rspec syntax `expect` because the old one (`should`) is deprecated. You might need to merge my previous PR if you want to test this by running `rspec` as you haven't added `simplecov` to `Gemfile` or `.gemspec`.

### CODE REVIEW

**Comment by kristianmandrup** [comment]
I was trying to run `bundle install` but problems installing nokogiri. However I don't see why that should be a dependency at all. I guess project needs some cleaning up! Thanks for helping! Haven't used ruby since 2013 tbh.

**Comment by kristianmandrup** [comment]
You are most welcome to fork it, improve it and publish it as `calc-haversine` or sth

**Comment by styd** [comment]
Kristian, I don't share your problem. But, it's probably because we still use the open-ended version for `jeweler`. The solution could be to use the non open-ended version ("~> 2.3") for the time being so you don't need to update `jeweler` and its dependencies, one of which is `nokogiri`.

**Comment by styd** [comment]
Kristian, as much as I like to improve it, I don't really have much ideas to offer to create it as a new gem as I also no longer use this gem in any project. However, I probably can help keep this gem up to date.

**Pull request merged**
